spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/localDB
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    schemas: public
jwt:
  token:
    secret: localnotes
    validityInMills: 3600000
    tokenPrefix: Bearer_