create table users
(
    id         bigint generated by default as identity primary key,
    public_id  varchar(255),
    username   varchar(255),
    email      varchar(255),
    password   varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    created    timestamp,
    updated    timestamp,
    status     varchar(255)
);

create table roles
(
    id        bigint generated by default as identity primary key,
    public_id varchar(255),
    name      varchar(255),
    status    varchar(255),
    created   timestamp,
    updated   timestamp
);

create table categories
(
    id          bigint generated by default as identity primary key,
    public_id   varchar(255),
    name        varchar(255),
    description varchar(255),
    status      varchar(255),
    user_id     varchar(255),
    created     timestamp,
    updated     timestamp
);

create table notes
(
    id          bigint generated by default as identity primary key,
    public_id   varchar(255),
    name        varchar(255),
    description varchar(255),
    favorite    boolean,
    status      varchar(255),
    user_id     varchar(255),
    created     timestamp,
    updated     timestamp,
    cat_id      bigint
);

create table user_roles
(
    user_id bigint not null,
    role_id bigint not null
);

alter table notes add constraint FK_category_id foreign key (cat_id) references categories;
alter table user_roles add constraint FK_user_id foreign key (user_id) references users;
alter table user_roles add constraint FK_role_id foreign key (role_id) references roles;